// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// random_unif_interval
NumericVector random_unif_interval(int size, int max_val);
RcppExport SEXP _SPARSim_random_unif_interval(SEXP sizeSEXP, SEXP max_valSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< int >::type max_val(max_valSEXP);
    rcpp_result_gen = Rcpp::wrap(random_unif_interval(size, max_val));
    return rcpp_result_gen;
END_RCPP
}
// random_unif_interval_seed
NumericVector random_unif_interval_seed(int size, int max_val, int input_seed);
RcppExport SEXP _SPARSim_random_unif_interval_seed(SEXP sizeSEXP, SEXP max_valSEXP, SEXP input_seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< int >::type max_val(max_valSEXP);
    Rcpp::traits::input_parameter< int >::type input_seed(input_seedSEXP);
    rcpp_result_gen = Rcpp::wrap(random_unif_interval_seed(size, max_val, input_seed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SPARSim_random_unif_interval", (DL_FUNC) &_SPARSim_random_unif_interval, 2},
    {"_SPARSim_random_unif_interval_seed", (DL_FUNC) &_SPARSim_random_unif_interval_seed, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_SPARSim(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
