# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

random_unif_interval <- function(size, max_val) {
    .Call('_SPARSim_random_unif_interval', PACKAGE = 'SPARSim', size, max_val)
}

random_unif_interval_seed <- function(size, max_val, input_seed) {
    .Call('_SPARSim_random_unif_interval_seed', PACKAGE = 'SPARSim', size, max_val, input_seed)
}

